import { Aleo } from "next/font/google";
import "./globals.css";
import Header from "../src/Header/Header.js";
import Footer from "../src/Footer/Footer.js";
import React from "react";

//imported Aleo as default font type
const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// created header and footer for root layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aleo.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
